spring:
  application:
    name: zuul-service 
 
jwt:
  header: Authorization
  secret: secret
  expiration: 604800 
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost      

    
server:
  port: 8080
  
zuul:
#service will be mapped under /api URI
  prefix: /api
  routes:
    auth-service:
      path: /auth/**
      service-id: http://localhost:8888
      strip-prefix: false
      sensitive-headers: Cookie,Set-Cookie
    driver-service:
      path: /driver/**
      url: http://localhost:8085
    employee-service:
      path: /employee/**
      service-id: http://localhost:8081
    transport-service:
      path: /transport/**
      service-id: http://localhost:8082
    vehicle-service:
      path: /vehicle/**
      service-id: http://localhost:8084
  